// The browser walk: every screen of every agent, end to end, against
// tools/browser_walk/demo_server.py. Needs Playwright and a Chromium.
//   python tools/browser_walk/demo_server.py &   then   node tools/browser_walk/walk.js
// Prints what it sees; 'errors: []' at the end means no page error.
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' }).catch(async () => chromium.launch());
  const page = await browser.newPage({ viewport: { width: 1100, height: 820 } });
  const errors = [];
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
  page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  page.on('response', (r) => { if (r.status() >= 400) console.log('http', r.status(), r.request().method(), new URL(r.url()).pathname); });
  const fs = require('fs'); fs.mkdirSync('shots', { recursive: true });
  const shot = (n) => page.screenshot({ path: `shots/${n}.png`, fullPage: true });

  await page.goto('http://127.0.0.1:8765/');
  await page.waitForSelector('#screen-start:not([hidden])');
  await page.waitForSelector('#recent-list p, #recent-list .recent-row');
  await shot('00-start');
  console.log('start tiles:', await page.locator('.tile').count(), '| address:', await page.textContent('#site-address'), '| open work:', (await page.textContent('#recent-list')).trim().slice(0, 60));

  // The shell (spec 11): the three status icons, their hover cards, the burger menu, the status page with the test call.
  await page.waitForSelector('#dot-vault.state-green', { timeout: 10000 });
  const dotClass = async (n) => (await page.getAttribute(`#dot-${n}`, 'class')).replace('dot ', '');
  console.log('status dots:', await dotClass('vault'), await dotClass('ai'), await dotClass('project'), '| chip:', await page.textContent('#project-chip-label'));
  await page.hover('#btn-status-vault');
  await page.waitForSelector('#card-vault', { state: 'visible' });
  console.log('vault card:', (await page.textContent('#card-vault')).replace(/\s+/g, ' ').slice(0, 120));
  await shot('00a-status-hover');
  await page.mouse.move(0, 400);
  await page.click('#btn-menu');
  await page.waitForSelector('#menu-list:not([hidden])');
  console.log('menu entries:', await page.locator('#menu-list [role=menuitem]').count(), '|',
    (await page.locator('#menu-list [role=menuitem]').allTextContents()).join(', '), '| obsidian link:', await page.getAttribute('#link-obsidian', 'href'));
  await shot('00b-menu');
  await page.keyboard.press('Escape');
  await page.click('#btn-status-vault');            // the status page comes from the icons now
  await page.waitForSelector('#status-dialog:not([hidden])');
  console.log('status rows:', await page.locator('#status-body .status-row').count(), '|', await page.textContent('#status-checked'));
  await page.click('#btn-status-test');
  await page.click('#btn-status-test-yes');
  await page.waitForFunction(() => /Test call/.test(document.querySelector('#status-body').textContent) && /answered/.test(document.querySelector('#status-body').textContent), null, { timeout: 15000 });
  console.log('after the test call:', await dotClass('ai'), '|', (await page.textContent('#status-body .status-row:nth-child(2) .status-detail')).trim());
  await shot('00c-status-dialog');
  await page.click('#btn-status-close');
  await page.click('#btn-status-ai');
  await page.waitForSelector('#status-dialog:not([hidden])');
  console.log('ai icon opens the status page with the test offer:', !(await page.locator('#status-test').isHidden()));
  await page.click('#btn-status-test-no');
  await page.click('#btn-status-close');

  await page.click('#btn-menu');
  await page.click('#btn-options');
  await page.waitForSelector('#options-dialog:not([hidden])');
  console.log('options sections:', (await page.locator('#options-nav button').allTextContents()).join(' | '),
    '| shown:', await page.locator('#options-panes fieldset:not([hidden])').count());
  await shot('02-options');
  await page.click('#options-nav button[data-pane="opt-model"]');
  console.log('after clicking Model:', await page.textContent('#options-panes fieldset:not([hidden]) legend'));
  await shot('02b-options-model');
  await page.click('#btn-options-cancel');

  console.log('picker label:', await page.textContent('#projects-label'));
  await page.click('#btn-projects');
  await page.waitForSelector('#projects-menu:not([hidden])');
  console.log('picker options:', await page.locator('#projects-list label').count());
  await page.check('#projects-list input[value="Sister"]');
  console.log('picker label after adding Sister:', await page.textContent('#projects-label'), '| chip:', await page.textContent('#project-chip-label'));
  await page.uncheck('#projects-list input[value="Sister"]');
  await shot('00-picker');
  await page.click('#btn-projects');
  await page.click('#tile-board');
  await page.waitForSelector('#screen-home:not([hidden])');
  console.log('board path:', new URL(page.url()).pathname, '| chip:', await page.textContent('#board-project'));
  await shot('01-home');
  await page.fill('#question', 'We must choose between reworking the Gen6 housing tooling at supplier X or switching to supplier Y. Budget is tight and the SOP date cannot move.');
  await page.click('#ask-form button[type=submit]');
  await page.waitForSelector('#screen-clarifying:not([hidden])');
  await shot('03-clarifying');
  await page.waitForSelector('#screen-questions:not([hidden])', { timeout: 15000 });
  await shot('04-questions');
  const answers = page.locator('#questions-form textarea');
  await answers.nth(0).fill('Yes, 10 weeks, which lands 2 weeks after SOP.');
  await page.click('#btn-answers');
  await page.waitForSelector('#screen-clarifying:not([hidden])');
  await page.waitForSelector('#screen-questions:not([hidden])', { timeout: 15000 });
  await shot('04b-questions-round2');
  console.log('round 2 intro:', await page.textContent('#questions-intro'));
  await page.locator('#questions-form textarea').nth(0).fill('Approved.');
  await page.click('#btn-answers');
  await page.waitForSelector('#screen-confirm:not([hidden])', { timeout: 15000 });
  await shot('05-confirm');
  console.log('picks:', await page.locator('#confirm-members input').count());
  console.log('selection dropdown:', await page.locator('#selection-mode').inputValue(), '| status:', await page.textContent('#pick-status'));
  await page.click('#btn-selection-info');
  console.log('selection info shown:', !(await page.locator('#selection-info').isHidden()), (await page.textContent('#selection-info')).slice(0, 60));
  await page.click('#btn-budget-info');
  console.log('budget info shown:', !(await page.locator('#budget-info').isHidden()));
  await page.waitForFunction(() => /chose the knowledge/.test(document.querySelector('#pick-status').textContent), null, { timeout: 15000 });
  console.log('pick landed:', await page.textContent('#pick-status'));
  await page.click('#estimate-detail summary');
  await page.waitForSelector('#estimate-notes .reason', { timeout: 10000 });
  console.log('AI pick marks:', await page.locator('#estimate-notes .mode-mark').count(), 'reasons:', await page.locator('#estimate-notes .reason').count(), 'core tags:', await page.locator('#estimate-notes .core-tag').count(), 'summary rows:', await page.locator('#estimate-notes .brief-tag').count());
  console.log('first reason:', await page.locator('#estimate-notes .reason').first().textContent());
  await shot('05a-ai-picks');
  await page.click('#btn-picks-python');
  await page.waitForTimeout(700);
  console.log('python only:', await page.locator('#selection-mode').inputValue(), '| marks now:', await page.locator('#estimate-notes .mode-mark').count(), '|', (await page.textContent('#pick-status')).slice(0, 50));
  await page.selectOption('#selection-mode', 'ai');
  await page.locator('#selection-mode').dispatchEvent('change');
  await page.waitForFunction(() => /chose the knowledge/.test(document.querySelector('#pick-status').textContent), null, { timeout: 15000 });
  await page.waitForTimeout(700);
  console.log('back to ai, marks:', await page.locator('#estimate-notes .mode-mark').count());
  await page.click('#estimate-detail summary');
  await page.uncheck('#confirm-members input[value="Mechanical Engineering"]');
  await page.waitForFunction(() => /model call/.test(document.querySelector('#estimate').textContent), null, { timeout: 10000 });
  console.log('estimate 6000:', await page.textContent('#estimate'));
  await page.locator('#budget').fill('3000');
  await page.locator('#budget').dispatchEvent('input');
  await page.waitForTimeout(600);
  console.log('estimate 3000:', await page.textContent('#estimate'));
  await page.click('#estimate-detail summary');
  console.log('per member:', (await page.textContent('#estimate-notes')).replace(/\s+/g, ' ').slice(0, 160));
  await page.waitForSelector('#outline input');
  await page.fill('#outline-filter', 'EMC');
  const emc = page.locator('#outline input[data-id="Lessons learned.md#EMC chamber booking"]');
  await emc.check();
  await page.waitForFunction(() => /your picks/.test(document.querySelector('#estimate').textContent), null, { timeout: 10000 });
  console.log('estimate with a pick:', (await page.textContent('#estimate')).slice(0, 120));
  await page.locator('#estimate-notes input').first().uncheck();
  await page.waitForTimeout(600);
  console.log('after excluding one section:', (await page.textContent('#estimate-notes')).replace(/\s+/g, ' ').slice(0, 120));
  await shot('05c-manual-picks');
  console.log('confirm line:', await page.textContent('#confirm-knowledge'));
  await shot('05b-confirm-unticked');
  await page.click('#btn-run');
  await page.waitForSelector('.member-tile.running', { timeout: 15000 });
  await page.waitForTimeout(1300);
  await shot('06-running');
  await page.waitForSelector('.member-tile.clickable', { timeout: 20000 });
  const stillThinking = await page.locator('.member-tile.running').count();
  await page.locator('.member-tile.clickable').first().click();
  await page.waitForSelector('.member-card');
  console.log('early read while thinking:', stillThinking, 'card:', await page.locator('.member-card .card-title').first().textContent());
  await shot('06a-early-answer');
  console.log('step line while the board works:', await page.textContent('#step-line'), '| current:', await page.textContent('.step.current .step-name'));
  await page.click('.step[data-step="2"]');
  await page.waitForSelector('#screen-confirm:not([hidden])', { timeout: 10000 });
  console.log('step back during the run -> confirm; result step clickable:', await page.locator('.step[data-step="3"].clickable').count() > 0);
  await page.waitForTimeout(2500);   // the stopped run must not surface a result
  console.log('still confirm after the run would have finished:', !(await page.locator('#screen-confirm').isHidden()));
  await page.click('#btn-run');
  await page.waitForSelector('.direction-tile.running', { timeout: 20000 });
  await shot('06b-consolidating');
  console.log('direction:', await page.textContent('#direction-state'));
  await page.waitForSelector('.direction-tile.done', { timeout: 30000 });
  await shot('07-result');
  console.log('tiles:', await page.locator('.member-tile').count(), 'na tiles:', await page.locator('.member-tile.na').count(), 'clickable:', await page.locator('.member-tile.clickable').count());
  await page.click('.member-tile[data-member="Finance"]');
  await page.click('.member-tile[data-member="SW Engineering"]');
  await shot('08-members-open');
  await page.click('.step[data-step="2"]');
  await page.waitForSelector('#screen-confirm:not([hidden])');
  console.log('back from the result; forward again offered:', await page.locator('.step[data-step="3"].clickable').count() > 0);
  await page.click('.step[data-step="3"]');
  await page.waitForSelector('.direction-tile.done', { timeout: 10000 });
  await shot('05d-step-line');
  console.log('back from result and forward again: ok | current step:', await page.textContent('.step.current .step-name'));
  await page.reload();
  await page.waitForSelector('.direction-tile.done', { timeout: 15000 });
  console.log('after reload:', await page.textContent('#result-topic'));
  await page.fill('#followup', 'Why does time beat the unit-cost saving?');
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  const before = await page.evaluate(() => window.scrollY);
  await page.click('#btn-followup');
  await page.waitForSelector('.turn.pending');
  await page.waitForTimeout(500);
  const during = await page.evaluate(() => window.scrollY);
  console.log('scroll before/during follow-up:', before, during);
  await page.waitForSelector('.turn:not(.pending)', { timeout: 15000 });
  await shot('09-followup');
  // the home page lists the open topic; one click brings it back
  await page.click('#btn-brand');
  await page.waitForSelector('#screen-start:not([hidden])');
  await page.waitForSelector('.recent-row[data-kind="board"]', { timeout: 10000 });
  console.log('board in open work:', (await page.textContent('.recent-row[data-kind="board"]')).replace(/\s+/g, ' ').trim().slice(0, 100), '| step line hidden off the board:', await page.locator('#step-line').isHidden());
  await page.click('.recent-row[data-kind="board"] .thread-meta');   // the whole row is one target
  await page.waitForSelector('.direction-tile.done', { timeout: 15000 });
  console.log('citation wording:', await page.locator('.sources li.warn').count(), 'to check ·', (await page.textContent('#synthesis-body')).includes('To check'));
  console.log('topic reopened from home:', new URL(page.url()).pathname, '| turns:', await page.locator('.turn').count(), '| step line back:', !(await page.locator('#step-line').isHidden()), '| current step:', await page.textContent('.step.current .step-name'));
  // second follow-up with two members asked again
  console.log('follow-up list:', await page.locator('#followup-members label').count(), 'not asked yet:', await page.locator('#followup-members label:has-text("not asked yet")').count());
  await page.check('#followup-members input[value="Finance"]');
  await page.check('#followup-members input[value="Manufacturing"]');
  console.log('hint:', await page.textContent('#result-hint'));
  console.log('follow-up pulled new pages:', await page.locator('.turn .fresh-pages').count(), '|', (await page.locator('.turn .fresh-pages').first().textContent().catch(() => 'none')).slice(0, 70));
  await page.fill('#followup', 'What if the rework is free of charge?');
  await page.click('#btn-followup');
  await page.waitForSelector('.turn.pending');
  await page.waitForSelector('.turn:nth-child(2):not(.pending)', { timeout: 20000 });
  await page.click('.turn:nth-child(2) details summary');
  await shot('09b-followup-members');
  await page.click('#btn-close');
  await page.waitForSelector('#close-dialog:not([hidden])');
  await shot('10-close-dialog');
  await page.click('#btn-close-yes');
  await page.waitForSelector('#screen-proposal:not([hidden])', { timeout: 15000 });
  await shot('11-proposal');
  await page.click('#btn-write');
  await page.waitForSelector('#screen-done:not([hidden])', { timeout: 15000 });
  await shot('12-written');
  console.log('written:', await page.textContent('#done-detail'));

  // a second topic in combined mode
  await page.click('#btn-new');
  await page.waitForSelector('#screen-home:not([hidden])');
  await page.fill('#question', 'Combined mode test: rework or switch?');
  await page.click('#ask-form button[type=submit]');
  await page.waitForSelector('#screen-questions:not([hidden])', { timeout: 15000 });
  await page.click('#btn-answers-final');
  await page.waitForSelector('#screen-confirm:not([hidden])', { timeout: 15000 });
  await page.click('#btn-mode-info');
  await page.selectOption('#run-mode', 'combined');
  console.log('combined confirm line:', (await page.textContent('#confirm-knowledge')).slice(-60));
  await shot('14-confirm-combined');
  await page.click('#btn-run');
  await page.waitForSelector('.direction-tile.done', { timeout: 30000 });
  console.log('combined state:', await page.textContent('#direction-state'), '|', await page.textContent('#board-state'));
  await page.locator('.member-tile.clickable').first().click();
  await shot('15-result-combined');
  await page.check('#followup-members input[value="Finance"]');
  await page.selectOption('#followup-mode', 'combined');
  console.log('combined follow-up hint:', await page.textContent('#result-hint'));
  await page.fill('#followup', 'And combined?');
  await page.click('#btn-followup');
  await page.waitForSelector('.turn:not(.pending)', { timeout: 20000 });
  console.log('combined turn:', (await page.textContent('.turn .members')));
  await page.click('#btn-menu');
  await page.click('#btn-stats');
  await page.waitForSelector('#stats-dialog:not([hidden])');
  console.log('stats:', await page.textContent('#stats-summary')); console.log('stats rows with pick:', await page.locator('#stats-body td:has-text("knowledge pick")').count(), 'split table:', await page.locator('#stats-body table.split').count());
  await shot('16-stats');
  await page.click('#btn-stats-close');
  await page.click('#btn-close');
  await page.waitForSelector('#close-dialog:not([hidden])');
  await page.click('#btn-close-no');
  await page.waitForSelector('#screen-done:not([hidden])', { timeout: 15000 });
  // Ask the vault (spec 10)
  await page.click('#btn-brand');
  await page.waitForSelector('#screen-start:not([hidden])');
  await page.click('#tile-ask');
  await page.waitForSelector('#screen-ask:not([hidden])');
  console.log('ask path:', new URL(page.url()).pathname, '| chip:', await page.textContent('#ask-project'), '| hint:', await page.textContent('#ask-hint'));
  await shot('20-ask');
  await page.fill('#ask-question', 'What has to be ready for the design freeze?');
  // Spec 5.7: the pages sit under the question box, before the thread exists.
  await page.waitForSelector('#ask-picker-home #ask-picker', { timeout: 10000 });
  await page.waitForSelector('#ask-estimate-notes .sec-list li', { state: 'attached', timeout: 10000 });
  console.log('pages under the new question:', await page.textContent('#ask-pages-summary'), '| estimate:', (await page.textContent('#ask-estimate')).slice(0, 80));
  await page.click('#ask-estimate-detail summary');
  await page.click('#ask-estimate-detail details.group[data-group="chosen"] > summary');
  await page.fill('#ask-outline-filter', 'lessons');
  console.log('filter "lessons" shows:', await page.locator('#ask-estimate-notes .sec-list li:not([hidden])').count(), 'row(s)');
  await page.fill('#ask-outline-filter', '');
  await shot('20b-pages');
  await page.click('#btn-ask-new');
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 15000 });
  console.log('thread path:', new URL(page.url()).pathname, '| picks screen shown:', !(await page.locator('#thread-picks-head').isHidden()),
    '| steps:', (await page.locator('#thread-steps .step').allTextContents()).join(' > '), '| answers so far:', await page.locator('.turn.answer').count());
  console.log('no slider on the thread page:', await page.locator('#screen-thread input[type=range]').count() === 0,
    '| the picker followed the question box:', await page.locator('#thread-form #ask-picker').count() === 1);
  // The steps (spec 5.4, decision 9) on the whole-vault path (spec 5.6): reading, writing, no check.
  await page.waitForFunction(() => /Reading \d+ notes/.test(document.querySelector('#thread-steps').textContent), null, { timeout: 15000 });
  console.log('steps while answering:', (await page.locator('#thread-steps .step').allTextContents()).join(' > '));
  // The answer as the model writes it (spec 4.1).
  await page.waitForSelector('#thread-live:not([hidden])', { timeout: 15000 });
  const early = (await page.textContent('#thread-live-text')).trim();
  await page.waitForFunction((was) => {
    const now = document.querySelector('#thread-live-text').textContent.trim();
    return now.length > was.length;
  }, early, { timeout: 15000 });
  console.log('live answer grew:', JSON.stringify(early.slice(0, 40)), '->', JSON.stringify((await page.textContent('#thread-live-text')).trim().slice(0, 60)));
  await shot('20c-answering');
  await page.waitForSelector('.turn.answer', { timeout: 20000 });
  await page.click('.turn.answer .sources-fold > summary');
  await shot('21-thread-answer');
  console.log('answer sources:', await page.locator('.turn.answer .sources a').count(), '| first link:', await page.locator('.turn.answer .sources a').first().getAttribute('href'),
    '| fold:', await page.textContent('.turn.answer .sources-fold > summary'));
  console.log('gaps:', await page.locator('.turn.answer .gaps li').count(), '| gap title:', await page.textContent('.turn.answer .gaps-title'), '| dropped note:', (await page.locator('.turn.answer .muted.small').count()) > 0, '| state:', await page.textContent('#thread-state'));
  console.log('read on the turn:', (await page.locator('.turn.answer .read-title').allTextContents()).join(' | '), '| loop shown:', await page.locator('.turn.answer .rounds').count());
  await page.waitForFunction(() => /model call/.test(document.querySelector('#ask-estimate').textContent), null, { timeout: 10000 });
  console.log('ask estimate:', await page.textContent('#ask-estimate'));
  await page.click('#ask-estimate-detail summary');
  await page.waitForSelector('#ask-estimate-notes .sec-list li', { state: 'attached', timeout: 10000 });
  console.log('ask pages:', await page.locator('#ask-estimate-notes .sec-list li').count(), 'core tags:', await page.locator('#ask-estimate-notes .core-tag').count());
  await page.click('#btn-ask-info');
  console.log('ask info shown:', !(await page.locator('#ask-info').isHidden()));
  // A question asked back: the same picker under the box, no separate step (spec 5.7).
  await page.fill('#thread-question', 'And who approves it?');
  await page.waitForTimeout(600);
  console.log('follow-up pages:', await page.textContent('#ask-pages-summary'), '| stop button hidden:', await page.locator('#btn-thread-cancel').isHidden());
  await shot('22a-follow-up-pages');
  await page.click('#btn-thread-ask');
  await page.waitForFunction(() => document.querySelectorAll('.turn.answer').length === 2, null, { timeout: 20000 });
  console.log('turns:', await page.locator('.turn.answer').count(), '| board hint:', await page.locator('.hint-board').count());
  await shot('22-thread-two-turns');
  // reload: deep link keeps the thread
  await page.reload();
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 15000 });
  console.log('after reload turns:', await page.locator('.turn.answer').count());
  await page.click('#btn-menu');
  await page.click('#btn-stats');
  await page.waitForSelector('#stats-dialog:not([hidden])');
  console.log('thread stats:', await page.textContent('#stats-summary'));
  await page.click('#btn-stats-close');
  // the home page lists the open thread and reopens it with one click
  await page.click('#project-chip');
  await page.waitForSelector('#screen-start:not([hidden])');
  console.log('chip opens the picker:', !(await page.locator('#projects-menu').isHidden()));
  await page.keyboard.press('Escape');
  await page.waitForSelector('.recent-row', { timeout: 10000 });
  console.log('open work rows:', await page.locator('.recent-row').count(), '|', (await page.textContent('.recent-row')).replace(/\s+/g, ' ').trim().slice(0, 100));
  await shot('26-home-open-work');
  await page.click('.recent-row[data-kind="ask"] .thread-meta');
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 15000 });
  console.log('reopened from home:', new URL(page.url()).pathname, '| turns:', await page.locator('.turn.answer').count());
  await page.click('#btn-menu');
  await page.click('#btn-stats');
  await page.waitForSelector('#stats-dialog:not([hidden])');
  await page.click('#btn-stats-close');
  // close with a note
  await page.click('#btn-thread-close');
  await page.waitForSelector('#thread-close-dialog:not([hidden])');
  await shot('23-close-dialog');
  await page.click('#btn-thread-close-yes');
  await page.waitForSelector('#screen-proposal:not([hidden])', { timeout: 15000 });
  console.log('proposal path:', await page.inputValue('#prop-path'));
  await page.click('#btn-write');
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 15000 });
  console.log('closed text:', await page.textContent('#thread-closed-text'));
  await shot('24-thread-closed');
  await page.click('#link-threads');
  await page.waitForSelector('#screen-ask:not([hidden])');
  console.log('open threads after closing:', await page.locator('#thread-list .thread-row').count(), '|', (await page.textContent('#thread-list')).trim().slice(0, 60));
  await shot('25-thread-list');
  // browser back and forward between the list and the closed thread
  await page.goBack();
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 10000 });
  console.log('after browser back path:', new URL(page.url()).pathname);
  await page.goForward();
  await page.waitForSelector('#screen-ask:not([hidden])', { timeout: 10000 });

  // The archive (spec 11.1, decision 10): everything closed, of both agents.
  await page.click('#btn-menu');
  await page.click('#btn-archive');
  await page.waitForSelector('#screen-archive:not([hidden])');
  await page.waitForSelector('.archive-row', { timeout: 10000 });
  const archived = await page.locator('.archive-row').count();
  console.log('archive path:', new URL(page.url()).pathname, '| rows:', archived, '|', await page.textContent('#archive-count'));
  console.log('archive agents:', await page.locator('.archive-row[data-kind="board"]').count(), 'board,', await page.locator('.archive-row[data-kind="ask"]').count(), 'ask');
  await shot('27-archive');
  console.log('archive tabs:', (await page.locator('#archive-tabs .tab').allTextContents()).join(' | '));
  await page.click('#archive-tabs .tab[data-kind="ask"]');
  await page.waitForFunction(() => document.querySelectorAll('.archive-row[data-kind="board"]').length === 0, null, { timeout: 10000 });
  console.log('ask tab:', await page.locator('.archive-row').count(), 'row(s) ·', await page.textContent('#archive-count'));
  await page.click('#archive-tabs .tab[data-kind="all"]');
  await page.waitForFunction(() => document.querySelectorAll('.archive-row[data-kind="board"]').length > 0, null, { timeout: 10000 });
  await page.fill('#archive-filter', 'design freeze');
  await page.waitForFunction(() => document.querySelectorAll('.archive-row').length === 1, null, { timeout: 10000 });
  console.log('search by title:', await page.textContent('#archive-count'), '|', (await page.textContent('.archive-row .thread-open')).slice(0, 40));
  await shot('28-archive-search');
  await page.click('.archive-row .agent-tag');
  await page.waitForSelector('#screen-thread:not([hidden])', { timeout: 10000 });
  console.log('closed thread readable from the archive:', await page.locator('.turn.answer').count(), 'turns · form hidden:', await page.locator('#thread-form').isHidden());
  await page.click('#btn-menu');
  await page.click('#btn-archive');
  await page.waitForSelector('.archive-row', { timeout: 10000 });
  await page.click('.archive-row[data-kind="board"] .thread-meta');
  await page.waitForSelector('.direction-tile.done', { timeout: 15000 });
  console.log('closed topic readable from the archive:', new URL(page.url()).pathname, '| closed note:', (await page.textContent('#board-closed-text')).slice(0, 60), '| follow-up hidden:', await page.locator('#followup-form').isHidden());
  await shot('29-archive-topic');
  await page.click('#btn-menu');
  await page.click('#btn-archive');
  await page.waitForSelector('.archive-row', { timeout: 10000 });
  page.once('dialog', (d) => d.accept());
  await page.click('.archive-row[data-kind="ask"] .archive-delete');
  await page.waitForFunction((n) => document.querySelectorAll('.archive-row').length === n - 1, archived, { timeout: 10000 });
  console.log('rows after delete:', await page.locator('.archive-row').count());
  // the topic survives a restart of the page: read back from the history folder
  await page.goto('http://127.0.0.1:8765/archive');
  await page.waitForSelector('.archive-row', { timeout: 10000 });
  console.log('archive after a reload:', await page.locator('.archive-row').count(), 'rows');

  // The written pages in the menu (spec 11.1, decisions 11 and 12).
  await page.click('#btn-menu');
  await page.click('#btn-privacy');
  await page.waitForSelector('#screen-privacy:not([hidden])');
  console.log('privacy path:', new URL(page.url()).pathname, '| cards:', await page.locator('#screen-privacy .privacy-card').count(), '|', await page.textContent('#screen-privacy .privacy-card h2'));
  await shot('30-privacy');
  await page.click('#btn-menu');
  await page.click('#btn-about');
  await page.waitForSelector('#screen-about:not([hidden])');
  console.log('about version:', await page.textContent('#about-version'), '| address:', (await page.textContent('#about-address')).slice(0, 34), '| spec:', await page.getAttribute('#about-spec a', 'href'), '| bug link:', await page.getAttribute('#link-bug', 'href'));
  await shot('31-about');
  const spec = await page.request.get('http://127.0.0.1:8765/spec');
  console.log('spec served:', spec.status(), spec.headers()['content-type'], (await spec.text()).slice(0, 28).replace(/\n/g, ' '));
  await page.goBack();
  await page.waitForSelector('#screen-privacy:not([hidden])');
  console.log('browser back from about ->', new URL(page.url()).pathname);
  // the same page on a phone: the columns stack, nothing is cut off (spec 12.1 decision 8)
  await page.setViewportSize({ width: 390, height: 840 });
  await page.goto('http://127.0.0.1:8765/');
  await page.waitForSelector('#screen-start:not([hidden])');
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
  console.log('phone width: horizontal overflow', overflow, 'px | status names hidden:', await page.locator('#btn-status-vault .status-name').isHidden());
  await shot('32-phone-home');
  await page.click('#tile-board');
  await page.waitForSelector('#screen-home:not([hidden])');
  await shot('33-phone-board');
  await page.setViewportSize({ width: 1100, height: 820 });

  // dark theme check
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.goto('http://127.0.0.1:8765/');
  await page.waitForSelector('#screen-start:not([hidden])');
  await shot('13-start-dark');
  console.log('errors:', JSON.stringify(errors));
  await browser.close();
})().catch((e) => { console.error('FAILED', e); process.exit(1); });
